Q1. Create two 3×3 matrices using the random function in Numpy and perform the following operations.
è Product (prod)
è Multiplication (multiply)
è Dot Product (dot)


In [10]:
import numpy as np
  
# 1st argument --> numbers ranging from 0 to 9, 
# 2nd argument, row = 2, col = 3
array1 = np.random.randint(10, size=(3, 3))
array2 = np.random.randint(10, size=(3, 3))
res = np.dot(array1,array2)
mul= array1* array2
prod=np.prod(array1,axis=0) * np.prod(array2,axis=1)
print(array1)
print(array2)
print(res)
print(mul)
print(prod)

[[0 9 1]
 [5 2 9]
 [3 8 0]]
[[9 4 2]
 [9 2 4]
 [2 2 5]]
[[83 20 41]
 [81 42 63]
 [99 28 38]]
[[ 0 36  2]
 [45  4 36]
 [ 6 16  0]]
[    0 10368     0]


Q2. Perform the following set operations using the Numpy functions.
è Union
è Intersection
è Set difference
è XOR


In [28]:
import numpy as np

A = np.array([1, 3, 5])
B = np.array([0, 2, 3])

union=np.union1d(A,B)
print("union:",union)

intersection=np.intersect1d(A,B)
print("intersection:",intersection)

set_diff=np.setdiff1d(A,B)
print("set difference:",set_diff)

xor=np.setxor1d(A,B)
print("xor:",xor)

union: [0 1 2 3 5]
intersection: [3]
set difference: [1 5]
xor: [0 1 2 5]


Q3. Create a 1D array using Random function and perform the following operations.
è Cumulative sum
è Cumulative Product
è Discrete difference (with n=3)
è Find the unique elements from the array


In [29]:
import numpy as np

array=np.random.randint(10,size=10)

print(array)

cumulativesum=np.cumsum(array)
print(cumulativesum)

product=np.cumprod(array)
print(product)

difference=np.diff(array, n=3)
print(difference)

unique=np.unique(array)
print(unique)

[2 8 1 3 7 3 9 0 7 8]
[ 2 10 11 14 21 24 33 33 40 48]
[   2   16   16   48  336 1008 9072    0    0    0]
[ 22  -7 -10  18 -25  31 -22]
[0 1 2 3 7 8 9]


Q4. Create two 1D array and perform the Addition using zip(), add() and user defined function (frompyfunc())


In [30]:
import numpy as np

array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([10, 20, 30, 40, 50])

result_zip = np.array([a + b for a, b in zip(array1, array2)])

result_np_add = np.add(array1, array2)

def user_defined_add(x, y):
    return x + y

ufunc = np.frompyfunc(user_defined_add, 2, 1)

result_user_defined = ufunc(array1, array2)

print("Array 1:", array1)
print("Array 2:", array2)
print("\nAddition using zip():", result_zip)
print("Addition using np.add():", result_np_add)
print("Addition using user-defined function:", result_user_defined)

Array 1: [1 2 3 4 5]
Array 2: [10 20 30 40 50]

Addition using zip(): [11 22 33 44 55]
Addition using np.add(): [11 22 33 44 55]
Addition using user-defined function: [11 22 33 44 55]


Q5. Find the LCM (Least Common Multiple) and GCD (Greatest Common Divisor) of an array of elements using reduce().


In [31]:
from functools import reduce
import math

def gcd(a, b):
    while b:
        a, b = b, a % b
    return a

def lcm(a, b):
    return a * b // gcd(a, b)

elements = [12, 18, 24, 36, 48]

gcd_result = reduce(gcd, elements)

lcm_result = reduce(lcm, elements)

print("Array of Elements:", elements)
print("GCD of Elements:", gcd_result)
print("LCM of Elements:", lcm_result)

Array of Elements: [12, 18, 24, 36, 48]
GCD of Elements: 6
LCM of Elements: 144
